### PR TITLE
Ensure we always win the games

### PR DESCRIPTION
**Pull request by ewpratten**
We can't lose

### CODE REVIEW

**Review by hyperliskdev — APPROVED** [review]
Its impossible, I've checked...

**Review by wm-c — APPROVED** [review]
Are we sure this will let us win hard enough? Might want to test it on the robot first.

**Review by soaosdev — APPROVED** [review]
It go win yes

**Review by rsninja722 — APPROVED** [review]

**Review by Keatonion — APPROVED** [review]

**Review by SRJacks — APPROVED** [review]
GOOD

**Comment by awpratten** [comment]
Let’s do it!!

**Pull request closed without merging**
