### PR TITLE
Add intake freezing feature

### PR DESCRIPTION
**Pull request by ewpratten**
Add the intake freezing feature requested by Tiet. This holds the intake in place at the very start of teleop and test modes. Pressing the intake button will un-freeze, and start intaking, then re-tuck

### CODE REVIEW

**Comment by ewpratten** [comment]
I threw on a small modification for less aggressive speeds on the intake arms

**Review by rsninja722 — APPROVED** [review]
looks good, I will be doing simulations tonight to try to fix the hopper in intake fixes

**Comment by ewpratten** [comment]
This commit should fix the CI errors. I removed an old dependency from the project.

**Comment by ewpratten** [comment]
> looks good, I will be doing simulations tonight to try to fix the hopper in intake fixes

Sounds good!

**Pull request merged**
