### PR TITLE
Intake fixes

### PR DESCRIPTION
**Pull request by rsninja722**
delay for intake start, and rumble controller when hopper is at capacity.

### CODE REVIEW

**Comment by hyperliskdev** [comment]
haha

**Comment by hyperliskdev** [comment]
nice

**Review by ewpratten — APPROVED** [review]
Nice! Have you tested this on the bot yet?

**Comment by ewpratten** [comment]
Once #170 is merged, we will convert your rumble code to use it. Possibly even create a helper class in Lib5k for custom rumble patterns

**Comment by rsninja722** [comment]
Yes, I quickly tested it once at the end of Saturday

**Comment by ewpratten** [comment]
ok. cool

**Pull request merged**
