### PR TITLE
Add support for climber hardware

### PR DESCRIPTION
**Pull request by ewpratten**
This PR:
 - Adds controls for climbing
 - Adds climb statemachine and subsystem

### CODE REVIEW

**Review by catarinaburghi — APPROVED** [review]

**Comment by ewpratten** [comment]
@catarinaburghi this has not actually been tested on the bot yet

**Comment by ewpratten** [comment]
Sarah has hooked up the hardware. I think we can test this

**Comment by ewpratten** [comment]
We need to rename the positions

**Review by catarinaburghi — APPROVED** [review]

**Review by slownie — APPROVED** [review]

**Comment by ewpratten** [comment]
Replaced in favour of #146

**Pull request closed without merging**
