### PR TITLE
Auton paths

### PR DESCRIPTION
**Pull request by wm-c**
Added path 2 and new PID values
path 2 scores from the center then grabs balls from the trench.

### CODE REVIEW

**Comment by wm-c** [comment]
Added today's changes, thanks for the help today @catarinaburghi

**Comment by ewpratten** [comment]
CI failed due to:
```
 /github/workspace/src/main/java/frc/robot/autonomous/Chooser.java:18: error: cannot find symbol
import frc.robot.autonomous.paths.slow.SlowRightTest;
                                      ^
  symbol:   class SlowRightTest
  location: package frc.robot.autonomous.paths.slow
/github/workspace/src/main/java/frc/robot/autonomous/Chooser.java:47: error: cannot find symbol
        m_pathChooser.addOption("Right side slow (half-field shot) Test", new SlowRightTest());
                                                                              ^
  symbol:   class SlowRightTest
  location: class Chooser
1 actionable task: 1 executed
```

Please fix

**Comment by wm-c** [comment]
I fixed the error and renamed a file

**Comment by wm-c** [comment]
This is ready for merging

**Pull request merged**
